# Generated by Django 4.2.4 on 2023-09-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resourcestag_resource_tag_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resourcestag',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
